CREATE DATABASE DB_MICROSERVICE_SCHEDULE;

USE DB_MICROSERVICE_SCHEDULE;

CREATE TABLE TB_PACIENT
(
	ID_PACIENT SERIAL PRIMARY KEY,
    DS_FIRST_NAME VARCHAR(50),
    DS_LAST_NAME VARCHAR(100),
    DS_CPF VARCHAR(15),
    DS_EMAIL VARCHAR(100)
);

CREATE TABLE TB_SCHEDULE
(
	ID_SCHEDULE SERIAL PRIMARY KEY,
    DS_DESCRIPTION VARCHAR(255),
    DT_SCHEDULING TIMESTAMP,
    DT_SCHEDULE_CREATED TIMESTAMP,
    ID_PACIENT BIGINT UNSIGNED NOT NULL,
    CONSTRAINT FK_TB_SCHEDULE_TB_PACIENT FOREIGN KEY (ID_PACIENT) REFERENCES TB_PACIENT(ID_PACIENT)
);